'use strict';
(function(){
if(window.DDRelicForgeCrafting)return;window.DDRelicForgeCrafting=1;
const SLOTS=['weapon','offhand','helm','armor','gloves','boots','ring','amulet','cloak','charm'],N={weapon:'Weapon',offhand:'Offhand',helm:'Helm',armor:'Armor',gloves:'Gloves',boots:'Boots',ring:'Ring',amulet:'Amulet',cloak:'Cloak',charm:'Charm'},RATE={common:[4,0,2],uncommon:[8,0,4],rare:[16,1,8],epic:[28,2,14],legendary:[45,4,24],mythic:[70,7,40]};
const L=()=>typeof SLOT_ORDER!='undefined'?SLOT_ORDER:SLOTS,A=v=>Array.isArray(v)?v:[],F=v=>typeof format=='function'?format(v):String(Math.floor(Number(v)||0)),H=v=>typeof escapeHtml=='function'?escapeHtml(v):String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),LOG=(s,t)=>{if(typeof pushLog=='function')pushLog(s,t)};
function init(s){if(!s||!s.player)return s;if(!s.town)s.town={};s.town.forgeTier=Math.max(1,Math.min(5,Math.floor(+s.town.forgeTier||1)));s.town.relicFavor=Math.max(0,Math.floor(+s.town.relicFavor||0));['forgeSpark','shards','ember'].forEach(k=>s.player[k]=Math.max(0,Math.floor(+s.player[k]||0)));s.player.inventory=A(s.player.inventory);s.player.discoveredGear=A(s.player.discoveredGear);return s}
function fav(s,n){init(s);let o=s.town.forgeTier;s.town.relicFavor+=Math.max(0,Math.floor(+n||0));s.town.forgeTier=Math.max(o,Math.min(5,1+Math.floor(s.town.relicFavor/120)));if(s.town.forgeTier>o)LOG(s,`Lowfire Forge reached Tier ${s.town.forgeTier}.`)}
function rix(r){return typeof rarityIndex=='function'?rarityIndex(r):Math.max(0,['common','uncommon','rare','epic','legendary','mythic'].indexOf(String(r||'common')))}
function cost(f){return f?{spark:1,shards:75,ember:1}:{spark:1,shards:40,ember:0}}
function ct(c){return [c.spark&&`${c.spark} spark`,c.shards&&`${c.shards} shards`,c.ember&&`${c.ember} ember`].filter(Boolean).join(' + ')}
function lvl(s,b){let raw=Math.max(1,+s.player.depth||0,+s.player.returnDepth||0,+s.player.safeExtractDepth||0),base=typeof threatDepthFromDepth=='function'?threatDepthFromDepth(raw):raw;return Math.max(1,Math.floor(base+(b||0)))}
function rare(i){if(!i||rix(i.rarity)>=rix('rare'))return i;i.rarity='rare';i.rating=Math.round((+i.rating||1)*1.22+4);if(i.stats)Object.keys(i.stats).forEach(k=>i.stats[k]=Math.round((+i.stats[k]||0)*1.18+1));i.value=Math.round((+i.value||0)*1.2+40);i.tags=Array.from(new Set(A(i.tags).concat(['forge-promoted'])));i.summary=(i.summary||'A Lowfire-crafted gear piece.')+' Forged above salvage grade.';return i}
function craft(s,slot,focus){init(s);let c=cost(focus);if(s.player.forgeSpark<c.spark||s.player.shards<c.shards||s.player.ember<c.ember)return LOG(s,`Need ${ct(c)}.`),null;let all=L(),chosen=all.includes(slot)?slot:(typeof pick=='function'?pick(all):all[Math.floor(Math.random()*all.length)]),raw=Math.max(1,Math.floor(+(s.player.depth||s.player.returnDepth||1)));s.player.forgeSpark-=c.spark;s.player.shards-=c.shards;s.player.ember-=c.ember;let item=rare(generateGear(chosen,lvl(s,focus?1+Math.floor(s.town.forgeTier/3):1),{source:'forge',depthRaw:raw,state:s}));item.source='forge';item.crafted=1;item.forgeTier=s.town.forgeTier;item.tags=Array.from(new Set(A(item.tags).concat(['crafted','lowfire-forge'])));item.summary=(item.summary||'A Lowfire-crafted gear piece.')+(focus?' Focused through a chosen slot pattern.':' Sparked from random salvage geometry.');s.player.inventory.unshift(item);if(!s.player.discoveredGear.includes(item.name))s.player.discoveredGear.push(item.name);fav(s,focus?12:7);LOG(s,`${focus?'Focused forge':'Forged'} ${item.name}.`);return item}
function eq(s,i){return!!(s.player.equipment&&i&&Object.values(s.player.equipment).some(x=>x&&x.id===i.id))}
function canSalvage(s,i){if(!i||i.kind==='special'||eq(s,i)||i.locked||i.favorite||i.protected)return 0;let r=String(i.rarity||'common').toLowerCase();return r==='common'||r==='uncommon'||A(i.tags).includes('junk')||A(i.tags).includes('starter')}
function salvage(s){init(s);let items=s.player.inventory.filter(i=>canSalvage(s,i));if(!items.length)return LOG(s,'No common or uncommon salvage is safe to break down.'),null;if(window.confirm&&!window.confirm(`Salvage ${items.length} safe items into forge materials?`))return null;let ids=new Set(items.map(i=>i.id)),sh=0,em=0,fa=0;items.forEach(i=>{let r=RATE[String(i.rarity||'common').toLowerCase()]||RATE.common,l=Math.max(1,Math.floor(+i.level||1));sh+=r[0]+Math.floor(l/4);em+=r[1];fa+=r[2]+Math.floor(l/8)});s.player.inventory=s.player.inventory.filter(i=>!ids.has(i.id));s.player.shards+=sh;s.player.ember+=em;fav(s,fa);LOG(s,`Salvaged ${items.length} items for ${sh} shards${em?` and ${em} ember`:''}.`);return{shards:sh,ember:em,favor:fa}}
function tcost(s,i){let n=Math.max(0,Math.floor(+i.tempered||0));return{shards:50+s.town.forgeTier*10+n*22,ember:1+Math.floor(n/2)}}
function temper(s,slot){init(s);let i=s.player.equipment&&s.player.equipment[slot];if(!i)return LOG(s,`Equip a ${(N[slot]||slot||'slot').toLowerCase()} before tempering.`),null;let cap=3+s.town.forgeTier,n=Math.max(0,Math.floor(+i.tempered||0)),c=tcost(s,i);if(n>=cap)return LOG(s,`${i.name} has reached this forge tier's temper limit.`),null;if(s.player.shards<c.shards||s.player.ember<c.ember)return LOG(s,`Need ${ct(c)} to temper ${i.name}.`),null;s.player.shards-=c.shards;s.player.ember-=c.ember;i.tempered=n+1;i.level=Math.max(+i.level||1,typeof normalizeItemLevel=='function'?normalizeItemLevel((+i.level||1)+1):(+i.level||1)+1);i.rating=Math.round((+i.rating||1)*1.075+3);if(i.stats)Object.keys(i.stats).forEach(k=>i.stats[k]=Math.round((+i.stats[k]||0)*1.055+1));i.value=Math.round((+i.value||0)*1.08+35);i.tags=Array.from(new Set(A(i.tags).concat(['tempered'])));i.summary=(i.summary||'A worn gear piece.')+` Tempered ${i.tempered}/${cap} by the Lowfire Forge.`;fav(s,9+i.tempered);LOG(s,`Tempered ${i.name} to +${i.tempered}.`);return i}
function buttons(s){let rows=L().map(slot=>({slot,item:s.player.equipment&&s.player.equipment[slot]})).filter(x=>x.item);if(!rows.length)return'<p class="small muted">Equip gear to unlock tempering.</p>';return`<div class="forge-grid">${rows.map(({slot,item})=>{let c=tcost(s,item),cap=3+s.town.forgeTier,n=Math.max(0,Math.floor(+item.tempered||0)),off=n>=cap||s.player.shards<c.shards||s.player.ember<c.ember?'disabled':'';return`<button class="ghost mini" data-temper-slot="${H(slot)}" ${off}>${H(N[slot]||slot)} +${n}/${cap}<br><span>${c.shards} shards + ${c.ember} ember</span></button>`}).join('')}</div>`}
function panel(s){init(s);let safe=s.player.inventory.filter(i=>canSalvage(s,i)).length;return`<div class="card-head"><div><h2>Lowfire Forge</h2><p>Salvage junk, focus gear slots, and temper equipped gear.</p></div><span class="pill rarity-rare">Tier ${F(s.town.forgeTier)}</span></div><div class="tag-row"><span class="pill">Spark ${F(s.player.forgeSpark)}</span><span class="pill">Shards ${F(s.player.shards)}</span><span class="pill">Ember ${F(s.player.ember)}</span><span class="pill">Forge Favor ${F(s.town.relicFavor)}</span></div><div class="sep"></div><div class="forge-grid"><button class="primary" id="forgeBtn">Forge Random<br><span>${H(ct(cost(0)))}</span></button><button class="ghost" id="salvageForgeBtn">Salvage Junk<br><span>${safe} safe items</span></button></div><div class="sep"></div><p class="small"><strong>Focused Forge</strong> costs ${H(ct(cost(1)))}.</p><div class="forge-grid">${L().map(slot=>`<button class="ghost mini" data-forge-slot="${H(slot)}">${H(N[slot]||slot)}</button>`).join('')}</div><div class="sep"></div><p class="small"><strong>Temper Equipped Gear</strong></p>${buttons(s)}<div class="sep"></div><p class="small muted">Forge Tier rises through forge favor from forging, salvage, and tempering.</p>`}
function css(){if(document.getElementById('ddForgeCss'))return;let st=document.createElement('style');st.id='ddForgeCss';st.textContent='#forgePanel .forge-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}#forgePanel button span{font-size:11px;opacity:.78}@media(max-width:560px){#forgePanel .forge-grid{grid-template-columns:1fr}}';document.head.appendChild(st)}
function bindForge(){css();let g=fn=>typeof runGuardedAction=='function'?runGuardedAction(fn):fn(),q=typeof $$=='function'?$$:sel=>Array.from(document.querySelectorAll(sel)),b=typeof el=='function'?el('salvageForgeBtn'):document.getElementById('salvageForgeBtn');if(b)b.onclick=()=>g(()=>{salvage(S);render()});q('[data-forge-slot]').forEach(btn=>btn.onclick=()=>g(()=>{craft(S,btn.dataset.forgeSlot,1);render()}));q('[data-temper-slot]').forEach(btn=>btn.onclick=()=>g(()=>{temper(S,btn.dataset.temperSlot);render()}))}
try{forgeItem=s=>craft(s,null,0)}catch(_){window.forgeItem=s=>craft(s,null,0)}
window.DungeonDexRelicForge={build:'1.4.8',craft,salvage,temper,ensure:init};css();if(typeof S!='undefined')init(S);if(typeof render=='function')render();
})();
